### ISSUE TITLE
The formula does not respect the rotation

### ISSUE THREAD

**Issue by kayvaninvemo** [manishboro/image-crop-and-zoom#2]
https://github.com/manishboro/image-crop-and-zoom/blob/9f0714e381296002fb6dff4f66fdfeab086d5ad2/src/utils/cropImage.js#L21

This function is correct only if the rotation is 0, unless the result will be not what is expected. I will try to solve the issue and create pull request.

**Comment by ValentinH** [comment]
You can check this official example from `react-easy-crop` which supports all rotations: https://codesandbox.io/s/q8q1mnr01w
